INSERT INTO ingredient (idingredient, nom_anglais, nom_francais) VALUES (1,'Havana Club rum','rhum Havana Club'),
 (2,'Kraken rum','rhum Kraken'),
 (3,'Tito''s vodka','vodka Tito''s'),
 (4,'l''Atelier''s vodka','vodka l''Atelier'),
 (5,'1769 MVodka Distillery','1769 Distillerie MVodka'),
 (6,'Hendrick''s gin','gin Hendrick''s'),
 (7,'Sauza Blue tequila','tequila Sauza Blue'),
 (8,'El Tesoro Platinum tequila','tequila El Tesoro Platinum'),
 (9,'Sauza 901 Silver tequila','tequila Sauza 901 Silver'),
 (10,'Grand Marnier','Grand Marnier'),
 (11,'Bulleit Frontier bourbon','bourbon Bulleit Frontier'),
 (12,'Disaronno amaretto','amaretto Disaronno'),
 (13,'Cointreau','Cointreau'),
 (14,'1642 Cola','1642 Cola'),
 (15,'soda','soda'),
 (16,'simple syrup','sirop simple'),
 (17,'agave syrup','sirop d''agave'),
 (18,'grenadine','grenadine'),
 (19,'Galliano Autentico','Galliano Autentico'),
 (20,'Angostura bitter','amer Angostura'),
 (21,'Jamaican #2 Bittercube bitter','amer Jamaican #2 Bittercube'),
 (22,'lemon juice','jus de citron'),
 (23,'lime juice','jus de lime'),
 (24,'orange juice','jus d''orange'),
 (25,'passionfruit juice','jus de fruit de la passion'),
 (26,'Joseph Cartron peach liquor','liqueur de pêche Joseph Cartron'),
 (27,'lime slices','rondelles de lime'),
 (28,'lime quarter','quartier de lime'),
 (29,'lime zest','zeste de lime'),
 (30,'lemon slices','rondelles de citron'),
 (31,'lemon zest','zeste de citron'),
 (32,'pineapple leaf','feuille d''ananas'),
 (33,'mint leaves','feuilles de menthe'),
 (34,'mint bouquet','bouquet de menthe'),
 (35,'raspberries','framboises'),
 (36,'Firebarns original sauce','sauce Firebarns originale'),
 (37,'Firebarns Tequila Lime sauce','sauce Firebarns Tequila Lime'),
 (38,'egg white','blanc d''oeuf'),
 (39,'salt','sel'),
 (40,'ground pepper','poivre du moulin');